"""Test definitions -> runnable pytest source.

This is the deterministic half of the pipeline. No LLM, no network, no clock,
no randomness: the same TestSuite renders to byte-identical source every time.
That property is load-bearing — the rendered files are committed, so
regenerating a suite produces a git diff, and that diff is a direct read on
whether the model's output is stable between runs.

The output is written as ordinary readable pytest rather than a data-driven
loop, for two reasons. A reviewer (or an auditor, given the traceability
requirement) can read a test and see what it asserts and which spec element it
came from. And a readable diff is a more useful stability signal than a
reshuffled JSON blob.
"""
import json
from typing import Any

from .schema import ContentType, SetupStep, TestDefinition, TestSuite

CONFTEST = '''\
"""Fixtures for the generated suite. Rendered by specforge — do not edit.

The suite talks HTTP to a running target rather than importing it. That keeps
the tool independent of the target's dependencies: specforge never needs
fastapi installed to test a FastAPI service, and the same suite would run
against the service deployed anywhere.
"""
import json
import os
import pathlib
import time

import httpx
import pytest

BASE_URL = os.environ.get("SPECFORGE_BASE_URL", "http://127.0.0.1:8000")
RESULTS_PATH = os.environ.get("SPECFORGE_RESULTS")

USER = ("specforge_user@example.com", "password123")
OTHER_USER = ("specforge_other@example.com", "password123")
# Registration always assigns the "user" role, so the admin cannot be created
# over the API. This account comes from the target's own seed data.
ADMIN = ("admin@specforge.dev", "password123")


def _token(email, password):
    """Register (ignoring "already exists") and exchange credentials for a token."""
    httpx.post(f"{BASE_URL}/auth/register", json={"email": email, "password": password})
    resp = httpx.post(
        f"{BASE_URL}/auth/token", data={"username": email, "password": password}
    )
    if resp.status_code != 200:
        raise RuntimeError(f"could not authenticate {email}: {resp.status_code} {resp.text}")
    return resp.json()["access_token"]


@pytest.fixture(scope="session")
def clients():
    """One HTTP client per identity, each with its auth header preset.

    Tests refer to identities by role, never by credential, so the executor
    owns how a role becomes a token.
    """
    built = {"none": httpx.Client(base_url=BASE_URL, timeout=10.0)}
    for role, (email, password) in (
        ("user", USER),
        ("other_user", OTHER_USER),
        ("admin", ADMIN),
    ):
        token = _token(email, password)
        built[role] = httpx.Client(
            base_url=BASE_URL,
            timeout=10.0,
            headers={"Authorization": f"Bearer {token}"},
        )
    yield built
    for client in built.values():
        client.close()


def pytest_runtest_logreport(report):
    """Append one JSON line per test outcome.

    A tiny hook rather than a reporting plugin: it keeps the tool's dependency
    list to what it actually needs, and gives the executor a stable format to
    parse across the repeated runs Phase 4 will do.
    """
    if RESULTS_PATH is None or report.when != "call":
        return
    line = {
        "test_id": report.nodeid.rsplit("::", 1)[-1],
        "outcome": report.outcome,
        "duration": round(report.duration, 4),
        "longrepr": str(report.longrepr)[:2000] if report.failed else None,
        "recorded_at": time.time(),
    }
    with pathlib.Path(RESULTS_PATH).open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(line) + "\\n")
'''

_HEADER = '''\
"""Generated by specforge from {title} v{version}. Do not edit.

{count} tests. Regenerate with:
    python -m specforge.cli render suite.json -o generated/
"""


'''


def _py(value: Any) -> str:
    """Render a Python literal deterministically.

    json.dumps with sorted keys gives stable output, and its scalars are valid
    Python for everything appearing in a JSON body except the three keywords.
    """
    text = json.dumps(value, sort_keys=True)
    for js, py in (("true", "True"), ("false", "False"), ("null", "None")):
        text = text.replace(js, py)
    return text


def _func_name(test_id: str) -> str:
    safe = "".join(c if c.isalnum() or c == "_" else "_" for c in test_id).strip("_")
    return f"test_{safe}" if not safe.startswith("test_") else safe


def _request_line(
    var: str,
    role: str,
    method: str,
    path: str,
    body: Any,
    query: Any,
    *,
    interpolate: bool,
    content_type: ContentType = ContentType.json,
) -> str:
    """One httpx call. `interpolate` marks the path as an f-string.

    The body keyword follows the content type: `json=` or, for form-encoded
    endpoints such as OAuth2 token exchange, `data=`. Getting this wrong makes
    the service answer 422 and reads as a service bug when it is an encoding
    mistake.
    """
    prefix = "f" if interpolate else ""
    args = [f'{prefix}"{path}"']
    if query:
        args.append(f"params={_py(query)}")
    if body is not None:
        keyword = "data" if content_type is ContentType.form else "json"
        args.append(f"{keyword}={_py(body)}")
    return f'    {var} = clients["{role}"].{method.lower()}({", ".join(args)})\n'


def _render_setup(steps: list[SetupStep]) -> tuple[str, dict[str, str]]:
    """Setup requests, plus the path params each one binds."""
    if not steps:
        return "", {}
    out = "    # setup: create the state this test needs, so it does not depend\n"
    out += "    # on execution order or on data left behind by another test.\n"
    bindings: dict[str, str] = {}
    for i, step in enumerate(steps):
        var = f"_setup{i}"
        out += _request_line(
            var,
            step.auth.value,
            step.method,
            step.path,
            step.body_dict(),
            None,
            interpolate=False,
            content_type=step.content_type,
        )
        out += (
            f'    assert {var}.status_code in (200, 201), '
            f'f"setup failed: {{{var}.status_code}} {{{var}.text}}"\n'
        )
        if step.capture and step.bind_to:
            out += f'    {step.bind_to} = {var}.json()["{step.capture}"]\n'
            bindings[step.bind_to] = step.bind_to
    return out + "\n", bindings


class RenderError(RuntimeError):
    """A definition that cannot be rendered into a runnable test."""


def render_test(test: TestDefinition) -> str:
    """One test definition -> one pytest function."""
    setup_src, bindings = _render_setup(test.setup)

    # Literal path params are substituted now. Ones bound by a setup step stay
    # as `{name}` and the call becomes an f-string, filled at runtime from the
    # setup response.
    path = test.resolved_path()
    unfilled = {
        seg.split("}")[0] for seg in path.split("{")[1:]
    } - set(bindings)
    if unfilled:
        # Fail at render time rather than emitting a request to a URL with a
        # literal brace in it, which would fail later for a confusing reason.
        raise RenderError(
            f"test '{test.id}' leaves path parameter(s) {sorted(unfilled)} unfilled: "
            "give a literal in path_params, or bind one from a setup step."
        )
    interpolate = bool(bindings) and "{" in path

    src = f"def {_func_name(test.id)}(clients):\n"
    src += f'    """{test.description}\n\n'
    src += f"    spec_ref   {test.spec_ref}\n"
    src += f"    case_type  {test.case_type.value}\n"
    src += f"    auth       {test.auth.value}\n"
    src += '    """\n'
    src += setup_src
    src += _request_line(
        "resp",
        test.auth.value,
        test.method,
        path,
        test.body_dict(),
        test.query_params_dict(),
        interpolate=interpolate,
        content_type=test.content_type,
    )
    src += (
        f"    assert resp.status_code == {test.expected_status}, \\\n"
        f'        f"expected {test.expected_status}, got {{resp.status_code}}: {{resp.text}}"\n'
    )

    expected_body = test.expected_body_dict()
    if expected_body:
        # List endpoints return an array, single-resource endpoints an object.
        # Normalising to a list means one assertion shape covers both: for a
        # collection the check becomes "some element matches", which is what a
        # test asserting its own created resource actually means.
        src += "    payload = resp.json()\n"
        src += "    items = payload if isinstance(payload, list) else [payload]\n"
        for key, value in sorted(expected_body.items()):
            # The failure message is a double-quoted f-string, so any double
            # quotes in the expected value would terminate it early. Single
            # quotes read the same to a human and can't break out.
            shown = _py(value).replace('"', "'")
            src += (
                f"    assert any(item.get({_py(key)}) == {_py(value)} for item in items), \\\n"
                f'        f"no item with {key}={shown} in {{payload}}"\n'
            )
    return src


def render_suite(suite: TestSuite) -> dict[str, str]:
    """Render a suite to {filename: source}. Pure — same input, same bytes."""
    tests = sorted(suite.tests, key=lambda t: t.id)
    body = _HEADER.format(title=suite.spec_title, version=suite.spec_version, count=len(tests))
    body += "\n\n".join(render_test(t) for t in tests)
    return {"conftest.py": CONFTEST, "test_suite.py": body}
